version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gulp-replace
    versions:
    - 1.1.0
  - dependency-name: "@stencil/core"
    versions:
    - 2.5.0
  - dependency-name: husky
    versions:
    - 5.2.0
